extends Node

const TILE_SIZE = Vector2(16,8);
const VISUALS_NODE_NAME = "Visuals"
const _GLOW_MODULATE_FACTOR = 1.5;
const GLOW_MODULATE = Color(_GLOW_MODULATE_FACTOR,_GLOW_MODULATE_FACTOR,_GLOW_MODULATE_FACTOR)
