extends Resource
class_name UpgradeTypes

enum types{
	DAMAGE_1,
	MINING_SPEED_1,
	
	DAMAGE_2,
	MINING_SPEED_2,
	MINION_AMOUNT_1,
	MINION_DAMAGE_1,
	
	ORB_AMOUNT_1,
	MINING_SPEED_3,
	DAMAGE_3,
	MINION_AMOUNT_2,
	MINION_DAMAGE_2,
	MINION_SCALING_1,
	
	DAMAGE_4,
	MINING_SPEED_4,
	MINION_DAMAGE_3,
	MINION_AMOUNT_3,
	MINION_SCALING_2,
	COLLECTOR_AMOUNT_1,
	MINION_AUTO_TARGET_1,
	ORB_DAMAGE_1,
	ORB_SCALING_1,
	
	DAMAGE_5,
	MINING_SPEED_5,
	MINION_DAMAGE_4,
	MINION_AMOUNT_4,
	MINION_SCALING_3,
	COLLECTOR_AMOUNT_2,
	ORB_SCALING_2,
	ORB_DAMAGE_2,
	COLLECTOR_SCALING_1,
	
	DAMAGE_6,
	MINING_SPEED_6,
	MINION_DAMAGE_5,
	MINION_AMOUNT_5,
	ORB_DAMAGE_4,
	MINION_SCALING_4,
	COLLECTOR_AMOUNT_3,
	ORB_SCALING_3,
	ORB_DAMAGE_3,
	COLLECTOR_SCALING_2,
}
